/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform --simplify
Author: matousekfoto (https://sketchfab.com/matousekfoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/banana-4d4c8d85a09b476c8136f0c4cd24c45a
Title: Banana
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Banana(props) {
  const { nodes, materials } = useGLTF("/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["ripe-banana_u1_v1"]}
        position={[-0.02, 5.75, -4.74]}
        rotation={[0.13, 0, 0.03]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
